# Generated by Django 5.2.7 on 2025-10-20 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='/avatars/default.jpg', upload_to='avatars')),
                ('summary', models.TextField(default='New user on our platform!', verbose_name='Summary about user')),
                ('location', models.TextField(default='Location is not specified.', verbose_name='Place of residence')),
                ('about', models.TextField(default='Apparently, this user prefers to keep an air of mystery about them.', verbose_name='About')),
                ('other_skills', models.TextField(blank=True, help_text='Comma-separated skills', null=True, verbose_name='Other skills')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Link name')),
                ('link', models.URLField(verbose_name='URL')),
                ('icon', models.TextField(choices=[('im im-github', 'GitHub'), ('im im-stackoverflow', 'StackOverflow'), ('im im-linkedin', 'LinkedIn'), ('im im-twitter', 'Twitter'), ('im im-globe', 'Website')], verbose_name='Icon name')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Skill name')),
                ('description', models.TextField(verbose_name='Skill description')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
            ],
        ),
    ]
