# Generated by Django 5.2.6 on 2025-10-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='resume_content',
            field=models.TextField(blank=True, help_text='Extracted content from resume', null=True, verbose_name='Resume Content'),
        ),
        migrations.AddField(
            model_name='account',
            name='resume_education',
            field=models.TextField(blank=True, help_text='Education extracted from resume', null=True, verbose_name='Resume Education'),
        ),
        migrations.AddField(
            model_name='account',
            name='resume_experience',
            field=models.TextField(blank=True, help_text='Experience extracted from resume', null=True, verbose_name='Resume Experience'),
        ),
        migrations.AddField(
            model_name='account',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Upload your resume/portfolio as DOCX file', null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='account',
            name='resume_skills',
            field=models.TextField(blank=True, help_text='Skills extracted from resume', null=True, verbose_name='Resume Skills'),
        ),
    ]
