# Generated by Django 5.2.6 on 2025-10-24 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account_resume_content_account_resume_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-proficiency_level', 'name']},
        ),
        migrations.AddField(
            model_name='account',
            name='availability_status',
            field=models.CharField(choices=[('open', 'Open to work'), ('busy', 'Busy'), ('available', 'Available for projects'), ('not_looking', 'Not looking')], default='available', help_text='Your current availability status', max_length=15, verbose_name='Availability Status'),
        ),
        migrations.AddField(
            model_name='account',
            name='experience_level',
            field=models.CharField(choices=[('junior', 'Junior (0-2 years)'), ('mid', 'Mid-level (3-5 years)'), ('senior', 'Senior (6+ years)')], default='junior', help_text='Select your experience level', max_length=10, verbose_name='Experience Level'),
        ),
        migrations.AddField(
            model_name='account',
            name='technology_stack',
            field=models.TextField(blank=True, help_text='Comma-separated technologies you work with (e.g., Python, React, Django)', null=True, verbose_name='Technology Stack'),
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiency_level',
            field=models.IntegerField(default=1, help_text='Skill level from 1 (Beginner) to 5 (Expert)', verbose_name='Proficiency Level'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Skill name'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.skillcategory'),
        ),
    ]
