# Generated by Django 5.2.6 on 2025-10-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_skillcategory_alter_skill_options_and_more'),
    ]

    operations = [
    ]
